version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app # backend/app フォルダをコンテナの /app に同期します
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Mac/Windowsでnode_modulesの同期による問題を避けるためのおまじない
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - ./frontend/.env